/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dragneel
 */
public class finishpanel extends javax.swing.JPanel {

    /**
     * Creates new form finishpanel
     */
    public finishpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scorelabel = new javax.swing.JLabel();
        thankyou2label = new javax.swing.JLabel();
        thankyou1label = new javax.swing.JLabel();
        developerpanel = new javax.swing.JLabel();
        developerpanel1 = new javax.swing.JLabel();
        developerpanel2 = new javax.swing.JLabel();
        developerpanel3 = new javax.swing.JLabel();
        developerpanel4 = new javax.swing.JLabel();
        developerpanel5 = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();

        setLayout(null);

        scorelabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        scorelabel.setForeground(new java.awt.Color(102, 0, 0));
        scorelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(scorelabel);
        scorelabel.setBounds(140, 290, 570, 60);

        thankyou2label.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        thankyou2label.setForeground(new java.awt.Color(102, 0, 0));
        thankyou2label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thankyou2label.setText("FOR PLAYING");
        add(thankyou2label);
        thankyou2label.setBounds(110, 180, 610, 80);

        thankyou1label.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        thankyou1label.setForeground(new java.awt.Color(102, 0, 0));
        thankyou1label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thankyou1label.setText("THANK YOU");
        add(thankyou1label);
        thankyou1label.setBounds(140, 70, 540, 80);

        developerpanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        developerpanel1.setForeground(new java.awt.Color(255, 255, 255));
        developerpanel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerpanel1.setText("- developed by");
        add(developerpanel1);
        developerpanel1.setBounds(370, 360, 220, 40);

        
        developerpanel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        developerpanel4.setForeground(new java.awt.Color(255, 255, 255));
        developerpanel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        developerpanel4.setText("Gurpreet Singh");
        add(developerpanel4);
        developerpanel4.setBounds(460, 480, 300, 40);

        

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finishback.jpg"))); // NOI18N
        add(imagelabel);
        imagelabel.setBounds(0, 0, 820, 620);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel developerpanel;
    private javax.swing.JLabel developerpanel1;
    private javax.swing.JLabel developerpanel2;
    private javax.swing.JLabel developerpanel3;
    private javax.swing.JLabel developerpanel4;
    private javax.swing.JLabel developerpanel5;
    private javax.swing.JLabel imagelabel;
    public static javax.swing.JLabel scorelabel;
    private javax.swing.JLabel thankyou1label;
    private javax.swing.JLabel thankyou2label;
    // End of variables declaration//GEN-END:variables
}
