/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author Dragneel
 */
public class namepanelclass extends javax.swing.JPanel {
    
    /**
     * Creates new form namepanelclass
     */
    //JTextField name1textfield=new JTextField();
    public namepanelclass() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namepanel = new javax.swing.JPanel();
        exeplorelabel = new javax.swing.JLabel();
        name1textfield = new javax.swing.JTextField();
        name1label = new javax.swing.JLabel();
        rollno1label = new javax.swing.JLabel();
        rollno1textfield = new javax.swing.JTextField();
        name2label = new javax.swing.JLabel();
        name2textfield = new javax.swing.JTextField();
        rollno2label = new javax.swing.JLabel();
        rollno2textfield = new javax.swing.JTextField();
        imagelabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(820, 580));

        namepanel.setMinimumSize(new java.awt.Dimension(825, 620));
        namepanel.setLayout(null);

        exeplorelabel.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        exeplorelabel.setForeground(new java.awt.Color(255, 0, 0));
        exeplorelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exeplorelabel.setText("EXEPLORE");
        namepanel.add(exeplorelabel);
        exeplorelabel.setBounds(90, 140, 620, 90);

        name1textfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name1textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1textfieldActionPerformed(evt);
            }
        });
        namepanel.add(name1textfield);
        name1textfield.setBounds(170, 340, 200, 30);
        name1textfield.getAccessibleContext().setAccessibleDescription("");

        name1label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name1label.setForeground(new java.awt.Color(255, 0, 0));
        name1label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1label.setText("NAME");
        namepanel.add(name1label);
        name1label.setBounds(50, 340, 90, 30);

        rollno1label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rollno1label.setForeground(new java.awt.Color(255, 0, 0));
        rollno1label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rollno1label.setText("ROLL NO.");
        namepanel.add(rollno1label);
        rollno1label.setBounds(50, 400, 120, 40);

        rollno1textfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namepanel.add(rollno1textfield);
        rollno1textfield.setBounds(170, 400, 200, 30);

        name2label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name2label.setForeground(new java.awt.Color(255, 0, 0));
        name2label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name2label.setText("NAME");
        namepanel.add(name2label);
        name2label.setBounds(400, 340, 100, 30);

        name2textfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namepanel.add(name2textfield);
        name2textfield.setBounds(530, 340, 190, 30);

        rollno2label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rollno2label.setForeground(new java.awt.Color(255, 0, 0));
        rollno2label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rollno2label.setText("ROLL NO.");
        namepanel.add(rollno2label);
        rollno2label.setBounds(410, 400, 110, 30);

        rollno2textfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namepanel.add(rollno2textfield);
        rollno2textfield.setBounds(530, 400, 190, 30);

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intro_1.jpg"))); // NOI18N
        namepanel.add(imagelabel);
        imagelabel.setBounds(0, 0, 820, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(namepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 820, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(namepanel, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void name1textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1textfieldActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_name1textfieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exeplorelabel;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JLabel name1label;
    public static javax.swing.JTextField name1textfield;
    private javax.swing.JLabel name2label;
    public static javax.swing.JTextField name2textfield;
    private javax.swing.JPanel namepanel;
    private javax.swing.JLabel rollno1label;
    public static javax.swing.JTextField rollno1textfield;
    private javax.swing.JLabel rollno2label;
    public static javax.swing.JTextField rollno2textfield;
    // End of variables declaration//GEN-END:variables
}
